server.port=8080
spring.application.name=interview_software
spring.data.mongodb.uri=mongodb+srv://techqa:techqa@alexnguyen.femtaem.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=sample_mflix
spring.data.mongodb.auto-index-creation=true
